version: "3"

services:
  app:
    build: .
    links:
      - db:db
    volumes:
    - ./app:/usr/src/app
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: "postgres:10"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

    ports:
      - "5432:5432"
    networks:
      - backend

  db-admin:
    image: dpage/pgadmin4
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge