# Generated by Django 3.0.8 on 2020-09-04 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('publication', models.FileField(upload_to='media/')),
                ('author', models.ManyToManyField(to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_author', to='accounts.Profile')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_publication', to='accounts.Publication')),
            ],
        ),
    ]
