# Generated by Django 3.0.8 on 2020-09-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200904_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.ManyToManyField(related_name='author_p', to='accounts.Profile'),
        ),
    ]
