# Generated by Django 3.0.8 on 2020-09-17 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_publication_author'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_c', to='publications.Publication', verbose_name='publication'),
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
